### ISSUE TITLE
create separate repos for collections

### ISSUE THREAD

**Issue by thedoubl3j** [ansible-collections/netapp#111]
##### SUMMARY

@thedoubl3j to create separate repos for the collections

##### ISSUE TYPE
- Administrative 

##### COMPONENT NAME

repos to be created:
```
Netapp.aws
Netapp.azure
Netapp.cloudmanager
Netapp.elementsw
Netapp.ontap
Netapp.storagegrid
Netapp.um_info
```

**Comment by carchi8py** [comment]
We will be preserving history. just to give the steps i did in our internal version to confirm this worked we will be doing something like this
`git filter-branch --prune-empty --subdirectory-filter ansible_collections/netapp/aws/ master`
This will strip all files/history except for the files/history in the subdirectory
then update the git remote origin to the new repo.
Then push to the new repo.

**Comment by lonico** [comment]
And maybe it goes without comment but the names should not be capitalized.  So we'd like to see

```
netapp.aws
netapp.azure
netapp.cloudmanager
netapp.elementsw
netapp.ontap
netapp.storagegrid
netapp.um_info
```

**Comment by thedoubl3j** [comment]
@carchi8py @lonico would you want to keep this repo and rename to um_info? or do you want a fresh repo and once this one is all cleaned out archive  it?

**Comment by thedoubl3j** [comment]
also, most of the repos are created with the netapp team added as maintainers. can your confirm you have the correct rights on the repos @carchi8py

**Comment by carchi8py** [comment]
![Screen Shot 2021-05-05 at 1 33 24 PM](https://user-images.githubusercontent.com/3905935/117205465-8572c600-ada6-11eb-9477-4b8ce8dea998.png)
I've only checked the ontap one, but in setting i dont have the same permissions i had before.

**Comment by thedoubl3j** [comment]
@carchi8py fixed, Maintainer -> Admin

**Comment by carchi8py** [comment]
OK cool. So our plan in the following

We will release 21.6.0 today in the existing repo https://github.com/ansible-collections/netapp. At which point i will freeze change to that repo

I'll then do the git commands to copy the history to each of the collection repo, and also make the same 21.6.0 in each of thouse. And new commit will go to through specific collection repos.

**Comment by thedoubl3j** [comment]
sounds good, I think I am missing one @carchi8py (repos) did you want to use this existing one to house a collection or create all new and archive this?

**Comment by carchi8py** [comment]
New one and achieve this one.

**Comment by thedoubl3j** [comment]
gotcha, should be done @carchi8py, let me know when to archive this repo.

**Comment by lonico** [comment]
@thedoubl3j Would you mind giving me admin permissions as well to the 7 repos?
