### ISSUE TITLE
na_ontap_cifs - add support for "comment" property

### ISSUE THREAD

**Issue by mamoep** [ansible-collections/netapp#112]
##### SUMMARY

The module na_ontap_cifs should support setting the property "comment". CLI equivalent `cifs share create -comment`
The property is available in ZAPI and REST API.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

na_ontap_cifs

##### ADDITIONAL INFORMATION

We use the comment field for additional documentation for our windows admins. Implementing this would help move our workflow to ansible.

```yaml

```

**Comment by lonico** [comment]
targeted for 21.7.0

**Comment by mamoep** [comment]
Feature was added with 21.7.0. Thank you very much!
