### ISSUE TITLE
na_ontap_cifs_vserver_security issues

### ISSUE THREAD

**Issue by markrob** [ansible-collections/netapp#16]
We have identifed 3 issues with the na_ontap_cifs_vserver_security module (new in 2.9)

1.	Int and string comparison
 
The module accepts a number of parameters, 4 of those specifically are of type “int”:
 
kerberos_clock_skew
kerberos_ticket_age
kerberos_renew_age
kerberos_kdc_timeout
 
 
However, the cifs_security_get_iter() function contained within that module returns the current value from the cluster as a string rather than an int.   This causes the module to fail when calling the get_modified_attribute() function as follows:
 
Traceback (most recent call last):
  File "/root/debug_dir/ansible/modules/storage/netapp/na_ontap_vserver_cifs_security.py", line 282, in <module>
    main()
  File "/root/debug_dir/ansible/modules/storage/netapp/na_ontap_vserver_cifs_security.py", line 278, in main
    obj.apply()
  File "/root/debug_dir/ansible/modules/storage/netapp/na_ontap_vserver_cifs_security.py", line 255, in apply
    modify = self.na_helper.get_modified_attributes(current, self.parameters)
  File "/usr/local/lib/python3.6/site-packages/ansible/module_utils/netapp_module.py", line 239, in get_modified_attributes
    elif cmp(value, desired[key]) != 0:
  File "/usr/local/lib/python3.6/site-packages/ansible/module_utils/netapp_module.py", line 53, in cmp
    return (a > b) - (a < b)
TypeError: '>' not supported between instances of 'str' and 'int'
 
The solution was simple, as per the code snippet below the return created by cifs_security_get_iter() can be updated to cast the string to int:
 
if result.get_child_by_name('num-records') and int(result.get_child_content('num-records')) > 0:
cifs_security_info = result.get_child_by_name('attributes-list').get_child_by_name('cifs-security')
      cifs_security_details['kerberos_clock_skew'] = int(cifs_security_info.get_child_content('kerberos-clock-skew'))
      cifs_security_details['kerberos_ticket_age'] = int(cifs_security_info.get_child_content('kerberos-ticket-age'))
      cifs_security_details['kerberos_renew_age'] = int(cifs_security_info.get_child_content('kerberos-renew-age'))
      cifs_security_details['kerberos_kdc_timeout'] = int(cifs_security_info.get_child_content('kerberos-kdc-timeout'))
 
2.	String and Boolean comparison
 
The same module also has several Boolean parameters.  When the cifs_security_get_iter() function retrieves the current values from the cluster it attempts to cast from string to Boolean.  However, this was not working properly as all string values were being casted to a Boolean value of true (regardless of whether the cluster returned string value “true” or “false”).  This is because bool(some_variable) will always equate to true provided that some_variable contains a string value.  The intent of the developer was clearly to cast string “false” to Boolean False, but Python does not work quite like that.  The end result is that the module always determined that a change was required even when one wasn’t (as the module parameters would always differ from the values returned form the cluster).   There are several solutions to this issue but the simplest of which we implemented was to use json.loads to perform the casting from string to Boolean as per the code snippet below:
 

            cifs_security_details['is_signing_required'] = json.loads(cifs_security_info.get_child_content('is-signing-required'))
            cifs_security_details['is_password_complexity_required'] = json.loads(cifs_security_info.get_child_content('is-password-complexity-required'))
            cifs_security_details['is_aes_encryption_enabled'] = json.loads(cifs_security_info.get_child_content('is-aes-encryption-enabled'))
            cifs_security_details['is_smb_encryption_required'] = json.loads(cifs_security_info.get_child_content('is-smb-encryption-required'))
            cifs_security_details['referral_enabled_for_ad_ldap'] = json.loads(cifs_security_info.get_child_content('referral-enabled-for-ad-ldap'))
            cifs_security_details['use_start_tls_for_ad_ldap'] = json.loads(cifs_security_info.get_child_content('use-start-tls-for-ad-ldap'))
            
3.  Missing parameter use_ldap_for_ad_ldap 

All of the cifs-securirty-modify  API parameters were available already with the exception of use_ldap_for_ad_ldap which we have added

**Comment by carchi8py** [comment]
This was fixed in the 19.10.1 release in this change https://github.com/ansible-collections/netapp/commit/5905a0d598dfda2a09baaa205bd0c2ba48b322bb#diff-2bda3fc97467e119079ebbfc7745f9d597541f8d507ba89f50d0c0a1a9e1a42a
