### ISSUE TITLE
na_ontap_firewall_policy missing portmap as a choice for service parameter

### ISSUE THREAD

**Issue by markrob** [ansible-collections/netapp#17]
The na_ontap_firewall_policy module (added in 2.7) is missing portmap as a possible choice for the service parameter.

We created an updated version of this which accepts portmap as a choice as per code snippet below:

service=dict(required=False, type='str', choices=['portmap', 'dns', 'http', 'https', 'ndmp',
                                                              'ndmps', 'ntp', 'rsh', 'snmp', 'ssh', 'telnet']),

**Comment by carchi8py** [comment]
This issue i believe was fixed by this change. https://github.com/ansible-collections/netapp/commit/c0ebfeeb08867e3f87923c0aa92b2ad200e45399#diff-86e740ae9977f83f0a7959db7645ddc0
