### ISSUE TITLE
na_ontap_vscan_on_access_policy missing option to enable the policy

### ISSUE THREAD

**Issue by markrob** [ansible-collections/netapp#18]
na_ontap_vscan_on_access_policy module (added in 2.8) doesn't provide the option to enable the newly created vscan on access policy.  The following code snippet shows how to enable the policy:

vscan_policy_status_obj = netapp_utils.zapi.NaElement("vscan-on-access-policy-status-modify")
vscan_policy_status_obj.add_new_child('policy-name', self.parameters['policy_name'])
vscan_policy_status_obj.add_new_child('policy-status', 'true')

However, it isn't quite as simple as just adding the code above.  The process of enabling a new on access policy as follows:

1.  Disable vscan for the vserver
2.  Disable the currently enabled on access policy
3.  Enable the newly created on access policy
4.  Enable vscan for the vserver

As such we have written a new module for enabling an on access vscan policy.

**Comment by lonico** [comment]
fixed in 20.8.0 collection (August 2020)
a5a4ea7c96adc4d9c9cd6e9aaf7f4345f6b371c9
