### ISSUE TITLE
na_ontap_command requirements are missing console permissions

### ISSUE THREAD

**Issue by nikolaykanov** [ansible-collections/netapp#22]
##### SUMMARY

The module requirements listed at https://docs.ansible.com/ansible/latest/modules/na_ontap_command_module.html#na-ontap-command-module do not mention that the user needs console access - admin is not enough.

See https://github.com/ansible/ansible/issues/65324 for the original report.
##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

na_ontap_command
##### ANSIBLE VERSION

```paste below
ansible 2.9.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug 29 2016, 10:12:21) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

**Comment by carchi8py** [comment]
We will add this to the required sections as well.

It is documented through in the module you listed (in the title at the top)
