### ISSUE TITLE
Check for missing commits vs devel

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/netapp#31]
##### SUMMARY
The "Big Migration" has now taken place.

As this collection already exists, we need to carefully check to see if any further commits went into devel since this repo was created.

Please check the contents of the following repos against this repo

* https://github.com/ansible-collection-migration/netapp.aws
* https://github.com/ansible-collection-migration/netapp.elementsw
* https://github.com/ansible-collection-migration/netapp.ontap

##### ISSUE TYPE
- Bug Report

**Comment by gundalow** [comment]
Clarification:
* Please do a per-file level diff against every file in the ansible-collection-migration repo and this one
* Pay care to files added and removed.
* During the last two weeks there have been lots of fixes, especially around and tests, dependencies, and new collection features e.g. meta/action_groups.yml

**Comment by gundalow** [comment]
I'm not sure which repo corresponds to https://github.com/ansible-collections/netapp/tree/master/ansible_collections/netapp/azure

**Comment by lonico** [comment]
We did not push the azure modules into https://github.com/ansible/ansible/tree/devel/lib/ansible/modules/cloud/azure

because we could not meet the requirements to run acceptance tests (or whatever they are called).   
The reason is that Azure ANF requires a subscription, and Red Hat would have to acquire a subscription to run these tests.

**Comment by gundalow** [comment]
The following modules are still in `community.general`, where as I believe they should be in one of the collections in this repo:

```
community/general/plugins/modules/storage/netapp (move_netapp)$ ls -1
na_cdot_aggregate.py
na_cdot_license.py
na_cdot_lun.py
na_cdot_qtree.py
na_cdot_svm.py
na_cdot_user.py
na_cdot_user_role.py
na_cdot_volume.py
na_ontap_gather_facts.py
netapp_e_alerts.py
netapp_e_amg.py
netapp_e_amg_role.py
netapp_e_amg_sync.py
netapp_e_asup.py
netapp_e_auditlog.py
netapp_e_auth.py
netapp_e_drive_firmware.py
netapp_e_facts.py
netapp_e_firmware.py
netapp_e_flashcache.py
netapp_e_global.py
netapp_e_hostgroup.py
netapp_e_host.py
netapp_e_iscsi_interface.py
netapp_e_iscsi_target.py
netapp_e_ldap.py
netapp_e_lun_mapping.py
netapp_e_mgmt_interface.py
netapp_e_snapshot_group.py
netapp_e_snapshot_images.py
netapp_e_snapshot_volume.py
netapp_e_storagepool.py
netapp_e_storage_system.py
netapp_e_syslog.py
netapp_e_volume_copy.py
netapp_e_volume.py
sf_account_manager.py
sf_check_connections.py
sf_snapshot_schedule_manager.py
sf_volume_access_group_manager.py
sf_volume_manager.py

```

If you let me know which collections they belong in I'll move the modules and tests.

**Comment by carchi8py** [comment]
@gundalow What the plan for the deprecated modules? I was told there wouldn't be a way to have deprecated modules in ansible collection until 2.10. The following are deprecated

na_cdot_aggregate.py
na_cdot_license.py
na_cdot_lun.py
na_cdot_qtree.py
na_cdot_svm.py
na_cdot_user.py
na_cdot_user_role.py
na_cdot_volume.py
na_ontap_gather_facts.py\sf_account_manager.py
sf_check_connections.py
sf_snapshot_schedule_manager.py
sf_volume_access_group_manager.py
sf_volume_manager.py

**Comment by gundalow** [comment]
Hi Chris,
As you rightly imply, when this NetApp collection was created we didn't have a mechanism to deprecate content in collections.

We now have the mechanism to do so, bumy creating a `meta/routing.yml` file in this repo which contains entries like this:

https://github.com/ansible-collections/community.general/blob/master/meta/routing.yml#L883

### PR1: NetApp repo
So, in this repo we need to add:
1. The modules, and any shared code (module_utils, etc)
2. Any integration or unit tests
3. Entries from `tests/sanity/ignore*.txt`
4. `meta/routing.yml`

I believe `s/community.general/netapp.COLLECTIONNAME/g` over the files should fix any imports, and tests, though careful review will be needed. 

### PR2: community.general repo
Delete the equilivent files 

### PR3: ansible/ansible
1. Update BOTMETA.yml so modules entries point to NetApp collection rather than community.general 
2. Update routing.yml so modules entries point to NetApp collection rather than community.general


If you would be happy to do PR1, I can do PR2 & PR3.

**Comment by carchi8py** [comment]
So with collection how will we keep deprecated modules around for. Will it still be 4 ansible release? Or how will that work.

**Comment by gundalow** [comment]
Exact cycle hasn't been defined, though we expect it to be something similar, yes.

**Comment by carchi8py** [comment]
Ok give me a day or 2 and I'll have PR1 done.

**Comment by gundalow** [comment]
Excellent, thank you.

**Comment by carchi8py** [comment]
@gundalow for the CDOT, and SF modules these are very very very old at this point can we just delete them?

**Comment by gundalow** [comment]
https://docs.ansible.com/ansible/latest/modules/sf_volume_manager_module.html looks like we can remove them in Ansible 2.11

I haven't checked if they are all due to be removed in 2.11

**Comment by carchi8py** [comment]
@gundalow Is it possible if we wanted to remove them earlier in the collection could we?

**Comment by gundalow** [comment]
> @gundalow Is it possible if we wanted to remove them earlier in the collection could we?

I'm not aware of us having done this before. One issue is we have no idea if people are still using these modules.

**Comment by carchi8py** [comment]
For us na_cdot_aggregate.py is the very very old version of the module of na_ontap_aggregate. (and all the na_cdot modules have a na_ontap version, all the sf modules have a na_elementsw version)

It uses the old API, we don't support it anymore, if there issues with these modules we don't fix it, and can't be 100% sure it even works anymore. The only time we do get e-mail about them tend to be from new customer who see them on the list (at the top since na_cdot will appear alphabetically before na_ontap) having issues getting something to work.

**Comment by gundalow** [comment]
Thanks for the background.

1) If the modules don't work at all they can be deleted. 
2) Can any of these modules move into this collection?
3) we could leave the modules in community.general and possibly copy the dependencies, such as Docs_fragments, module_utils, etc so community.genersl no longer depends on any of the NetApp collections.

**Comment by lonico** [comment]
The cdot and sf Modules are really old.   They provide really little value and I’m pretty sure they are not used.   We see very little traction on our improved modules for ElementSW that are superseded the sf ones.  And we have a lot of questions on our ONTAP modules but none on the cdot ones.  So I don’t think any of these modules is actively used.   I would rather not include them in our collections to avoid any confusion.

**Comment by gundalow** [comment]
Hi, given the above we'd like to propose that the NetApp modules that are in `community.general` stay in community.general and we copy the dependencies from this repo into community.general to avoid the dependency.

This has been done in https://github.com/ansible-collections/community.general/pull/76 thanks to @felixfontein for doing this.

Do any of the modules there need to be moved into the NetApp Collections?

**Comment by carchi8py** [comment]
@gundalow , @felixfontein  thanks. netapp_e_* module i'm working with the developer for that one, they have a different Repo for that, and we are working on them to figure out where they are going to put it in galaxy, I'll get back you on that one soon.

**Comment by carchi8py** [comment]
@gundalow, @felixfontein  I've been out for a few days is there anything left to do for this change?
Our series team netapp_e_* module should have or are in the process of making this change.

For the old/dead modules na_cdot* and sf_* i think you guy added them to the community version. Just so you're aware we don't know if these work or not, they use an old unsupported API. We don't have test for them either, so we don't know if they work or not. Which is why we would like them deleted, but i'll let you guys make that call if it going in the community version.  

if there nothing else to do let me know if i can close this issue.

**Comment by felixfontein** [comment]
@carchi8py I think everything's done.
