### ISSUE TITLE
na_ontap_vserver_create failover policy for iscsi lifs

### ISSUE THREAD

**Issue by zhenyatsk** [ansible-collections/netapp#45]
##### SUMMARY

na_ontap_vserver_create creates lifs for nfs without proper failover_policy

https://github.com/ansible-collections/netapp/blob/bcc925d19ead6f2ea6fe7dcaa0d24cfb42370e85/ansible_collections/netapp/ontap/roles/na_ontap_vserver_create/tasks/main.yml#L68
tries to create interface with failover_policy 'local-only' for nfs / cifs. Looks like extra "not".
iscsi lifs must not have failover_policy because of multipathing

we have to change this line to and it works ok:
    failover_policy: "{{ omit if item.protocol.lower() is search('iscsi') else 'system-defined' }}"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
na_ontap_vserver_create task list

##### EXPECTED RESULTS
system-defined failover policy for none iscsi protocols (for example nfs/cifs).

**Comment by carchi8py** [comment]
@zhenyatsk thanks for the feedback, we made this change and will be pushed it out to github later today (it will be part of the august release)

**Comment by zhenyatsk** [comment]
Thank you.

**Comment by carchi8py** [comment]
This change was pushed out in this change
https://github.com/ansible-collections/netapp/commit/551c013efa3df40bc04e52773a33bdc42409f51e#diff-f80cdc3df6f1031ee7f6269436b84e20
