### ISSUE TITLE
na_ontap_info: add security relevant information

### ISSUE THREAD

**Issue by mamoep** [ansible-collections/netapp#46]
##### SUMMARY
I would like to gather information of the following cli commands:
- "event notification show"
- "event notification destination show"
- "cluster log-forwarding show" 
- "cifs options show"
- "security login role show"
- "security login role config show"

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Module: na_ontap_info

##### ADDITIONAL INFORMATION
I need it for daily security configuration auditing.

**Comment by carchi8py** [comment]
I'll add a story to add these into a future release

**Comment by mamoep** [comment]
Added with 20.12.0 https://github.com/ansible-collections/netapp/releases/tag/20.12.0

Many thanks!
