### ISSUE TITLE
wrong vserver in Create Intercluster Lif task

### ISSUE THREAD

**Issue by zhenyatsk** [ansible-collections/netapp#48]
##### SUMMARY
wrong vserver in - name: Create Intercluster Lif

https://github.com/ansible-collections/netapp/blob/a9a6b889e19679ee6e26f3db09d00d185da89fee/ansible_collections/netapp/ontap/roles/na_ontap_cluster_config/tasks/main.yml#L195 
line should be "vserver: Intercluster"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
na_ontap_cluster_config

##### EXPECTED RESULTS
intercluster lif created

##### ACTUAL RESULTS
Task fail with error. 

I have created using web and intercluster lifs got associated with vserver named Intercluster.
```
****-*****::> network interface show -lif inter_lif_0
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Intercluster
            inter_lif_0  up/up    x.y.z.v/24      ****-*****-01 
                                                                   a0a-212 true
```

**Comment by lonico** [comment]
According to David, this is working as designed.

"{{ cluster }}"   is a variable, and you can set the cluster name as you desire.

**Comment by zhenyatsk** [comment]
@lonico i think it's a bad idea to set cluster name to "Intercluster". There are a lot of diff places that used hardcoded values.

**Comment by schmots1** [comment]
Cluster name is set to what ever you name the cluster. This puts the kids on each defined node as part of the cluster vserver and makes them usable for snapmirror. This inter cluster LIFs and not intracluster LIFs which are the cluster backbone

**Comment by zhenyatsk** [comment]
Yes, i am tring to setup snapmirror and try to create intercluster lifs for that purpose, but after creating configuration part for example tasks i got an error. After that i tried to create that lifs using web interface, after that i have discovered that web interface create lifs on vserver "Intercluster".

**Comment by lonico** [comment]
Please use our #configurationmgmt channel on Slack for any usage question.

The registration link can be found on https://netapp.io
