### ISSUE TITLE
ONTAP module for managing LIF service policies

### ISSUE THREAD

**Issue by AdrianBronder** [ansible-collections/netapp#64]
##### SUMMARY
There is no module for managing service policies (available since ONTAP 9.5). Probably the most common use-case is creating a custom service policy or modify an existing one as there is no built-in policy in ONTAP allowing management as well as data traffic on a single LIF.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- Proposal: na_ontap_interface_service_policy

##### ADDITIONAL INFORMATION
- Service policy parameter already included in na_ontap_interface for assigning a service policy to a LIF
- Link to documentation: https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-49B18DFB-D154-40D2-9B83-D85182068259.html

**Comment by YvosOnTheHub** [comment]
+1

**Comment by scaleoutsean** [comment]
@YvosOnTheHub - check out reactions (right hand side of the comment pane), it helps lower unnecessary issue activity notifications for the devs and others

![image](https://user-images.githubusercontent.com/16622642/96149044-7415b980-0f3b-11eb-9f02-1d6955908f68.png)

**Comment by lonico** [comment]
We already have a story for this, but we postponed it because there was not REST support.
The APIs were added in 9.8 for POST/PATCH/DELETE.

**Comment by lonico** [comment]
Released in 21.7.0

fixed in ansible-collections/netapp.ontap@ab93b0f5348f627c75c3c165956d6902140851da
