### ISSUE TITLE
na_ontap_quotas and quota resize?

### ISSUE THREAD

**Issue by AndySilvia** [ansible-collections/netapp#70]
##### SUMMARY
We were able to set quotas with this module, but when we add quotas later oder modify them, it seems that "quota resize" is not done - is there any way to get this working without some kind of workaround ("send command via ssh or something like this")?

Or we are doing things wrong...

Example output from ansible run about the options:

```
 "changed": true, 
    "invocation": { 
        "module_args": { 
            "disk_limit": "65GB", 
            "file_limit": "-", 
            "hostname": "svm-xyz", 
            "http_port": null, 
            "https": true, 
            "ontapi": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "policy": "default", 
            "qtree": "", 
            "quota_target": "/vol/test/toast", 
            "set_quota_status": true, 
            "state": "present", 
            "threshold": "-", 
            "type": "tree", 
            "use_rest": "Auto", 
            "username": "user", 
            "validate_certs": false, 
            "volume": "spicetest", 
            "vserver": "svm-xyz" 
        } 
    } 
} 

```

Thanks in advance for you support...

AndySilvia

**Comment by lonico** [comment]
We are actively working on adding this capability.

In the meantime, you could use the na_ontap_command volume.
```
command: "quota resize -vserver {{ vserver_name }} -volume spicetest"
```

**Comment by AndySilvia** [comment]
Thanks for your answer - we worked around exactly as you suggested... ;)

Good to hear, that you are working on this...

Should/can this thread be closed?

Bye,

AndySilvia

**Comment by lonico** [comment]
Closing.   Workaround is working as expected, and the change is scheduled for our next release.
