### ISSUE TITLE
Updating documentation with Python library requirements

### ISSUE THREAD

**Issue by AdrianBronder** [ansible-collections/netapp#72]
##### SUMMARY
Documentation not stating netapp-lib as dependency for working with the ONTAP modules provided in collections

##### ISSUE TYPE
- Documentation on Galaxy (Details/Read Me)
- Documentation on GitHub (Readme.md)

##### COMPONENT NAME
https://github.com/ansible-collections/netapp/blob/master/ansible_collections/netapp/ontap/README.md
https://github.com/ansible-collections/netapp/blob/master/README.md

##### ANSIBLE VERSION
n/a

**Comment by lonico** [comment]
Requirements are documented at the module level, eg:

https://docs.ansible.com/ansible/latest/collections/netapp/ontap/na_ontap_active_directory_module.html#ansible-collections-netapp-ontap-na-ontap-active-directory-module

But I agree it would not hurt to add something in the README.

**Comment by carchi8py** [comment]
i'll go ahead and add it to the read me.

**Comment by AdrianBronder** [comment]
Thank you very much! :) It was raised during a workshop and I also thought it was valid to have it documented at this level. Again, thanks for picking it up so quickly!

**Comment by carchi8py** [comment]
This change should come out today on github and will be part of our 21.1.0 release at the start of next month on ansible-galaxy.

**Comment by lonico** [comment]
fixed with #69b7c6752c7e8c6a713ea08ae1f4384588a3dd43
