### ISSUE TITLE
[RFE] Need module to automate the ontap volume access management commands

### ISSUE THREAD

**Issue by SWADESNA** [ansible-collections/netapp#73]
##### SUMMARY

We are looking to automate the below ontap volume access management commands to perform the below tasks.

1) Assign / share / grant access a newly created volume to a host node
2) Check on which and all node a particular vol share is assigned / granted access to
2) Check on which and all node a particular vol share is mounted on currently. 
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- na_ontap

**Comment by lonico** [comment]
Could you be more specific on the commands you are looking for?
For instance, if you're using ONTAP CLI, which commands are sent?

1. should be available through export policies, na_ontap_export_policy and na_ontap_export_policy_rule for NFS.
2. should be available though na_ontap_info:  export_policy_info, export_rule_info
3. I'm not sure you can know this in ONTAP, as the mount happens on the host.  Or I misunderstood what you are looking for.

**Comment by carchi8py** [comment]
@SWADESNA could you give the details above?

**Comment by carchi8py** [comment]
Closing this story since we haven't got feedback from the requestor to look into it.
