### ISSUE TITLE
Add diagnostic privilege's when running ontap_command

### ISSUE THREAD

**Issue by idan-tankel** [ansible-collections/netapp#78]
##### SUMMARY

Hey all,
I've found out that there is no option to run onatp commands in diagnostic mode via na_ontap_command module, even though the option is supported by the python library being used.
Is there a special reason for it?

##### ISSUE TYPE
- Question & Feature Idea

##### COMPONENT NAME

na_ontap_command.py

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by lonico** [comment]
na_ontap_command supports a privilege option, but the zapi only allows for two values, admin or advanced.

You can still manually prepend the command with `set diag;`  for example
command: 'set diag;version'

Is there any reason to use diag mode?  This can be pretty dangerous, and not something we want to encourage.

**Comment by idan-tankel** [comment]
I did change the available options and added 'diagnostic' to the static list in the na_ontap_command module
Then I wrote a simple task with 
`privilege : diagnostic`
**It works!** 

After that, I have run successfully a command to retrieve recovery queue (this command is available only in diagnostic mode)
`volume recovery-queue show` 
and a similar commands.... 
I used it to simply restore a few volumes from the queue and to do some rename and restore simple procedures

> Is there any reason to use diag mode? This can be pretty dangerous, and not something we want to encourage.

As I said this option is sort of possible via the current tools
So I think It would be great to add this option, I don't think it's bad to add option that is already "available"

**Comment by carchi8py** [comment]
I'm going to close this, we don't plan to allow Diagnostic mode to the ansible modules.
