### ISSUE TITLE
Remove azure requirements

### ISSUE THREAD

**Issue by anshulbehl** [ansible-collections/netapp#89]
##### SUMMARY

As the collection already depends on azure collection you can remove the azure requirements from this collection
##### ISSUE TYPE
- Bug Report

**Comment by anshulbehl** [comment]
cc: @carchi8py

**Comment by carchi8py** [comment]
We have a change for this internal that we'll push out soon.

**Comment by anshulbehl** [comment]
Should be hold out the azure collection to be released to AH because of this issue?

**Comment by carchi8py** [comment]
No go ahead and push it out we'll have the fix in the 21.4.0 version (the change should be getting to pushed in to github in a few minutes)

**Comment by anshulbehl** [comment]
ok , I have pushed it out, but this needs to be fixed otherwise we won't be able to build execution environment when including the netapp azure collection

**Comment by lonico** [comment]
fixed with aa350e9fc349f75695cb32da8d8a88d7425fadfe
