### ISSUE TITLE
No requirement name solidfire on pypi

### ISSUE THREAD

**Issue by anshulbehl** [ansible-collections/netapp#91]
##### SUMMARY
elementsw and ontap require solidfire as a requirement which doesn't exist on pypi, can it be solidfire-sdk-python?
Requirements file in both the collections needs to be fixed accordingly
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by anshulbehl** [comment]
cc: @carchi8py

**Comment by carchi8py** [comment]
Yes that correct let me fix that. (The package is called solidfire-sdk-python, but the import is solidfire). I copied everything from out import statements. Should have a fix in a day or so

**Comment by carchi8py** [comment]
There a fix internally getting reviewed for this, will get pushed out automatically once it approved.

**Comment by lonico** [comment]
fixed by  bd77b48cb61771730563d9849d8266fe657cf2a8
