### ISSUE TITLE
Update test matrix and add sanity/ignore-2.12.txt if applicable

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/netapp#98]
##### SUMMARY
Copied from https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100

## stable-2.11 has been branched

The ansible/ansible repository now has a `stable-2.11` branch, and the version of the `devel` branch has been bumped to `2.12.0.dev0`. This means that if you have an `tests/sanity/ignore-2.11.txt` file in your collection, you need to copy it to `tests/sanity/ignore-2.12.txt`. Also if your collection is included in Ansible, please make sure that CI also tests against the new `stable-2.11` branch. Ansible 4.0.0 will be based on ansible-core 2.11, and thus your collection must work with `stable-2.11`.

(We still recommend to also test against the `devel` branch to be informed early about breaking changes. But testing against `stable-2.11` is **required** by the [inclusion criteria](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst), now that `stable-2.11` exists.)

**Comment by Andersson007** [comment]
cc @carchi8py

**Comment by carchi8py** [comment]
@Andersson007 

For 2.12.0.dev0 the only way to get that would be to clone the git repo? (there isn't a way to pip install it).

I'll add that first to our internal pipeline, and then see if i can get the git clone to work in action. 


![Screen Shot 2021-04-08 at 8 09 53 AM](https://user-images.githubusercontent.com/3905935/114051656-2458e080-9842-11eb-959e-82198d2a8216.png)

**Comment by Andersson007** [comment]
@carchi8py thanks!

**Comment by lonico** [comment]
Addressed with https://github.com/ansible-collections/netapp/pull/101

**Comment by Andersson007** [comment]
@lonico I see the PR has been merged, can we close the issue?

**Comment by carchi8py** [comment]
yes i'll go ahead and close this.

**Comment by Andersson007** [comment]
@carchi8py @lonico cool, thanks!
